### PR TITLE
chore: organize at_mono workflows and module structure

### PR DESCRIPTION
**Pull request by xavierchanth**
**- What I did**

- moved each git submodule from modules/ to modules/dart
- added the c/at_c module
- updated the paths in melos.yaml
- removed all auto-commit actions
- changed the daily backup job to a weekly one that does a pr, rather than forever living as an isolated date branch
  - pr includes the date so we still have some way of viewing historical commits easily by reading the name of the merge commit

**- How I did it**

**- How to verify it**

**- Description for the changelog**
chore: organize at_mono workflows and module structure

### CODE REVIEW

**Comment by xavierchanth** [comment]
I made a mistake, these are no longer showing up as submodules

**Comment by xavierchanth** [comment]
Fixed the submodules problem with https://github.com/atsign-foundation/at_mono/pull/46/commits/c4d652509e108017f8c04241a5e4dbd61de92198

**Comment by xavierchanth** [comment]
@cpswan @JeremyTubongbanua There was a bunch of tech debt here, it should all be cleaned up now.

**Comment by xavierchanth** [comment]
Ready for review @cpswan @JeremyTubongbanua

**Review by cpswan — APPROVED** [review]

**Pull request merged**
